sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: ${OSS_ACCESS_KEY_ID}
    access-key-secret: ${OSS_ACCESS_KEY_SECRET}
    bucket-name: javazsj
  redis:
    host: localhost
    port: 6379
    database: 10
    password: 123456
  wechat:
    appid: wxa7cce327064d8ea4
    secret: 932975cd5946a518b44521171f54fc16
    notifyUrl: https://1d7a3547.r30.cpolar.top/notify/paySucess
    refundNotifyUrl: https://1d7a3547.r30.cpolar.top/notify/refundSucess